# Generated by Django 5.1.4 on 2025-01-06 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Faction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("faction_name", models.CharField(max_length=100)),
                ("reroll_value", models.IntegerField()),
                ("apo_available", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="League",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("managers", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="PlayerType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("position", models.CharField(max_length=100)),
                ("max_quantity", models.IntegerField()),
                ("price", models.IntegerField()),
                ("movement", models.IntegerField()),
                ("strength", models.IntegerField()),
                ("agility", models.IntegerField()),
                ("armour", models.IntegerField()),
                ("starting_skills", models.CharField(max_length=100)),
                ("normal_skill_access", models.CharField(max_length=100)),
                ("double_skill_access", models.CharField(max_length=100)),
                (
                    "faction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_types",
                        to="league_manager.faction",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("coach", models.CharField(max_length=100)),
                (
                    "league",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="league_manager.league",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="None", max_length=100)),
                ("position", models.CharField(default="None", max_length=100)),
                ("value", models.IntegerField(default=0)),
                ("movement", models.IntegerField(default=0)),
                ("strength", models.IntegerField(default=0)),
                ("agility", models.IntegerField(default=0)),
                ("armour", models.IntegerField(default=0)),
                ("skills", models.CharField(default="None", max_length=100)),
                (
                    "normal_skill_access",
                    models.CharField(default="None", max_length=100),
                ),
                (
                    "double_skill_access",
                    models.CharField(default="None", max_length=100),
                ),
                ("injuries", models.CharField(default="None", max_length=100)),
                (
                    "player_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="league_manager.playertype",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="league_manager.team",
                    ),
                ),
            ],
        ),
    ]
