# Generated by Django 5.1.4 on 2025-01-07 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("league_manager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="faction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="league_manager.faction",
            ),
        ),
    ]
