# Generated by Django 5.1.4 on 2025-01-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("league_manager", "0002_team_faction"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="apothecary",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="team",
            name="assistant_coaches",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="team",
            name="cheerleaders",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="team",
            name="fan_factor",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="team",
            name="rerolls",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="team",
            name="treasury",
            field=models.IntegerField(default=0),
        ),
    ]
