# Generated by Django 5.1.4 on 2025-01-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("league_manager", "0003_team_apothecary_team_assistant_coaches_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="status",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("Retired", "Retired"),
                    ("Dead", "Dead"),
                ],
                default="Active",
                max_length=10,
            ),
        ),
    ]
