# Generated by Django 5.1.4 on 2025-01-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("league_manager", "0004_player_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="playertype",
            name="number",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
