# Generated by Django 5.1.4 on 2025-01-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("league_manager", "0006_remove_playertype_number_player_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="casualties",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="player",
            name="interceptions",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="player",
            name="miss_next",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="player",
            name="mvps",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="player",
            name="pass_completions",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="player",
            name="touchdowns",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="player",
            name="injuries",
            field=models.CharField(default="", max_length=100),
        ),
    ]
