# Generated by Django 5.1.4 on 2025-01-07 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("league_manager", "0007_player_casualties_player_interceptions_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="league_manager.league",
                    ),
                ),
                (
                    "result",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="league_manager.team",
                    ),
                ),
                (
                    "team1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches_as_team1",
                        to="league_manager.team",
                    ),
                ),
                (
                    "team1_tds",
                    models.ManyToManyField(
                        related_name="tds_as_team1", to="league_manager.player"
                    ),
                ),
                (
                    "team2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches_as_team2",
                        to="league_manager.team",
                    ),
                ),
                (
                    "team2_tds",
                    models.ManyToManyField(
                        related_name="tds_as_team2", to="league_manager.player"
                    ),
                ),
            ],
        ),
    ]
