# Generated by Django 5.1.4 on 2025-01-13 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("league_manager", "0009_remove_match_result_remove_match_team1_tds_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="touchdown",
            name="team",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_touchdowns",
                to="league_manager.team",
            ),
        ),
    ]
