# Generated by Django 5.1.4 on 2025-01-13 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("league_manager", "0010_touchdown_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("invalid", "Invalid"),
                ],
                default="in_progress",
                max_length=15,
            ),
        ),
    ]
