# Generated by Django 5.1.4 on 2025-01-15 10:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("league_manager", "0011_match_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="touchdowns",
        ),
    ]
