# Generated by Django 5.1.4 on 2025-01-15 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("league_manager", "0012_remove_player_touchdowns"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="pass_completions",
        ),
        migrations.CreateModel(
            name="PassCompletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_completion",
                        to="league_manager.match",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receiver_completion",
                        to="league_manager.player",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_completion",
                        to="league_manager.team",
                    ),
                ),
                (
                    "thrower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thrower_completion",
                        to="league_manager.player",
                    ),
                ),
            ],
        ),
    ]
