# Generated by Django 5.1.4 on 2025-01-18 23:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("league_manager", "0016_auto_20250117_1112"),
    ]

    operations = [
        migrations.AddField(
            model_name="injurytype",
            name="niggling",
            field=models.BooleanField(default=False),
        ),
    ]
