# Generated by Django 5.1.4 on 2025-01-19 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("league_manager", "0017_injurytype_niggling"),
    ]

    operations = [
        migrations.AlterField(
            model_name="injury",
            name="match",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="match_injuries",
                to="league_manager.match",
            ),
        ),
    ]
