# Generated by Django 5.1.4 on 2025-01-19 00:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("league_manager", "0018_alter_injury_match"),
    ]

    operations = [
        migrations.AddField(
            model_name="injurytype",
            name="description",
            field=models.CharField(default="-", max_length=20),
        ),
    ]
