# Generated by Django 5.1.4 on 2025-01-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("league_manager", "0020_match_team1_fame_match_team2_fame_match_weather"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="team1_fanfactor_change",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="match",
            name="team1_winnings",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="match",
            name="team2_winnings",
            field=models.IntegerField(default=0),
        ),
    ]
