# Generated by Django 3.2.5 on 2025-01-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_manager', '0022_match_team2_fanfactor_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='double_skill_access',
            field=models.CharField(default='None', max_length=10),
        ),
        migrations.AlterField(
            model_name='player',
            name='normal_skill_access',
            field=models.CharField(default='None', max_length=10),
        ),
        migrations.AlterField(
            model_name='player',
            name='skills',
            field=models.CharField(default='None', max_length=250),
        ),
        migrations.AlterField(
            model_name='playertype',
            name='double_skill_access',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='playertype',
            name='normal_skill_access',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='playertype',
            name='starting_skills',
            field=models.CharField(max_length=200),
        ),
    ]
