# Generated by Django 3.2.5 on 2025-01-30 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league_manager', '0023_auto_20250121_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelUpType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('ma_modifier', models.IntegerField(default=0)),
                ('st_modifier', models.IntegerField(default=0)),
                ('ag_modifier', models.IntegerField(default=0)),
                ('av_modifier', models.IntegerField(default=0)),
                ('skill', models.CharField(default='', max_length=20)),
                ('category', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('scheduled', 'Scheduled'), ('invalid', 'Invalid')], default='scheduled', max_length=15),
        ),
        migrations.CreateModel(
            name='LevelUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_up_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league_manager.leveluptype')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_levels', to='league_manager.player')),
            ],
        ),
    ]
