# Generated by Django 3.2.5 on 2025-01-31 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league_manager', '0024_auto_20250130_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelup',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_ups', to='league_manager.player'),
        ),
    ]
