# Generated by Django 3.2.5 on 2025-01-31 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_manager', '0025_alter_levelup_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leveluptype',
            name='skill',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
