# Generated by Django 3.2.5 on 2025-01-31 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_manager', '0026_alter_leveluptype_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leveluptype',
            name='skill',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
