# Generated by Django 5.1.5 on 2025-02-01 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_manager', '0027_alter_leveluptype_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='icon_path',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
