# Generated by Django 5.1.5 on 2025-02-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_manager', '0028_faction_icon_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='playertype',
            name='icon_path',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
