# Generated by Django 5.1.5 on 2025-02-01 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_manager', '0029_playertype_icon_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(default='', max_length=20)),
                ('description', models.TextField()),
            ],
        ),
    ]
