# Generated by Django 5.1.5 on 2025-02-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_manager', '0030_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playertype',
            name='double_skill_access',
        ),
        migrations.RemoveField(
            model_name='playertype',
            name='normal_skill_access',
        ),
        migrations.RemoveField(
            model_name='playertype',
            name='starting_skills',
        ),
        migrations.AddField(
            model_name='playertype',
            name='double_skill_access',
            field=models.ManyToManyField(related_name='double_skill_players', to='league_manager.skill'),
        ),
        migrations.AddField(
            model_name='playertype',
            name='normal_skill_access',
            field=models.ManyToManyField(related_name='normal_skill_players', to='league_manager.skill'),
        ),
        migrations.AddField(
            model_name='playertype',
            name='starting_skills',
            field=models.ManyToManyField(related_name='starting_skill_players', to='league_manager.skill'),
        ),
    ]
