# Generated by Django 5.1.5 on 2025-02-01 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_manager', '0031_remove_playertype_double_skill_access_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playertype',
            name='double_skill_access',
        ),
        migrations.RemoveField(
            model_name='playertype',
            name='normal_skill_access',
        ),
        migrations.AddField(
            model_name='playertype',
            name='double_skill_access',
            field=models.CharField(default='G', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playertype',
            name='normal_skill_access',
            field=models.CharField(default='G', max_length=10),
            preserve_default=False,
        ),
    ]
