# Generated by Django 3.2.5 on 2025-02-01 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_manager', '0032_remove_playertype_double_skill_access_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='skills',
        ),
        migrations.AddField(
            model_name='player',
            name='skills',
            field=models.ManyToManyField(related_name='skill_players', to='league_manager.Skill'),
        ),
    ]
