# Generated by Django 3.2.5 on 2025-02-02 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_manager', '0033_auto_20250201_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
