# Generated by Django 5.1.5 on 2025-02-02 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league_manager', '0034_player_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playertype',
            name='icon_path',
        ),
    ]
