# Generated by Django 3.2.5 on 2025-02-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_manager', '0035_remove_playertype_icon_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='current',
            field=models.BooleanField(default=False),
        ),
    ]
