# Generated by Django 4.2.18 on 2025-02-05 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("league_manager", "0036_league_current"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatIncrease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="stat_increase", max_length=25)),
                ("value", models.IntegerField(default=0)),
                ("ma_modifier", models.IntegerField(default=0)),
                ("st_modifier", models.IntegerField(default=0)),
                ("ag_modifier", models.IntegerField(default=0)),
                ("av_modifier", models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name="levelup",
            name="level_up_type",
        ),
        migrations.AddField(
            model_name="levelup",
            name="skill",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="league_manager.skill",
            ),
        ),
        migrations.AddField(
            model_name="levelup",
            name="stat_increase",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="league_manager.statincrease",
            ),
        ),
    ]
