# Generated by Django 4.2.18 on 2025-02-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("league_manager", "0037_statincrease_remove_levelup_level_up_type_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LevelUpType",
        ),
        migrations.AddField(
            model_name="levelup",
            name="level_number",
            field=models.IntegerField(default=0),
        ),
    ]
